'''
common/locators.py consists all the element locators used in TestCases/test_file.py
'''

all_tabs = "div.category-cards"
book_store_tab_name = "(//div[@class='card-body'])[6]"
book_store_tab = "//body//div//div[6]"
book_page_header = "//div[@class='main-header']"
search_box = "input[id='searchBox']"
git_book = "Git Pocket Guide"
git_author = "(//div[@role='gridcell'])[3]"
author_field = "//div[@class='profile-wrapper']//div[1]//div[1]"
author_name_field = "(//label[@class='form-label'])[8]"
elements_tab_name = "(//div[@class='card-body'])[1]"
elements_tab = "(//div[@class='card-up'])[1]"
radio_button = "(//span[@class='text'])[3]"
radio_btn_l = "(//label[@for='yesRadio'])[1]"
radio_result = "(//p[@class='mt-3'])[1]"
widget = "(//div[@class='card-body'])[4]"
widget_tab = "(//div[@class='card-up'])[4]"
tabs = "(//span[@class='text'])[21]"
tab1 = "//a[@data-rb-event-key='what']"
tab2 = "//a[@data-rb-event-key='use']"
tab_msg = "(//div[@class='tab-content'])[1]"
alert = "(//div[@class='card-body'])[3]"
alert_tab = "(//div[@class='card-up'])[3]"
alerts_op = "(//span[@class='text'])[12]"
click_me = "(//button[@type='button'][normalize-space()='Click me'])[3]"
message = "(//span[@class='text-success'])[1]"