'''
common/locators.py consists all the element locators used in TestCases/test_file.py
'''

ALL_TABS = "div.category-cards"
BOOK_STORE_TAB_NAME = "(//div[@class='card-body'])[6]"
BOOK_STORE_TAB = "//body//div//div[6]"
BOOK_PAGE_HEADER = "//div[@class='main-header']"
SEARCH_BOX = "input[id='searchBox']"
GIT_BOOK = "Git Pocket Guide"
GIT_AUTHOR = "(//div[@role='gridcell'])[3]"
AUTHOR_FIELD = "//div[@class='profile-wrapper']//div[1]//div[1]"
AUTHOR_NAME_FIELD = "(//label[@class='form-label'])[8]"
ELEMENTS_TAB_NAME = "(//div[@class='card-body'])[1]"
ELEMENTS_TAB = "(//div[@class='card-up'])[1]"
RADIO_BUTTON = "(//span[@class='text'])[3]"
RADIO_BTN_L = "(//label[@for='yesRadio'])[1]"
RADIO_RESULT = "(//p[@class='mt-3'])[1]"
WIDGET = "(//div[@class='card-body'])[4]"
WIDGET_TAB = "(//div[@class='card-up'])[4]"
TABS = "(//span[@class='text'])[21]"
TAB1 = "//a[@data-rb-event-key='what']"
TAB2 = "//a[@data-rb-event-key='use']"
TAB_MSG = "(//div[@class='tab-content'])[1]"
ALERT = "(//div[@class='card-body'])[3]"
ALERT_TAB = "(//div[@class='card-up'])[3]"
ALERTS_OP = "(//span[@class='text'])[12]"
CLICK_ME = "(//button[@type='button'][normalize-space()='Click me'])[3]"
MESSAGE = "(//span[@class='text-success'])[1]"
